// Generated by CoffeeScript 1.7.1
(function() {
  var bitstate, exports;

  bitstate = function(_arg) {
    var check, init, methods, set_false, set_true, val, _ref;
    _ref = _arg != null ? _arg : {}, init = _ref.init, set_true = _ref.set_true, set_false = _ref.set_false, check = _ref.check;
    val = init != null ? init : true;
    methods = {};
    methods[check || "is"] = function(check) {
      return val === check;
    };
    methods[set_true || "yes"] = function() {
      return val = true;
    };
    methods[set_false || "no"] = function() {
      return val = false;
    };
    return methods;
  };

  if (typeof exports !== "undefined" && exports !== null) {
    if ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) {
      exports = module.exports = bitstate;
    }
    exports["bit-state"] = bitstate;
  } else {
    this["bit-state"] = bitstate;
  }

}).call(this);
